### PR TITLE
rosbridge_tcp: added periodic diagnostic update to rosbridge_tcp as a…

### PR DESCRIPTION
**Pull request by ianrust**

### CODE REVIEW

**Comment by ianrust** [comment]
@shashwatak

**Comment by shashwatak** [comment]
awesome

**Comment by shashwatak** [comment]
FUCK sorry I merged it on accident thinking you were PR onto my branch

**Comment by shashwatak** [comment]
i reverted it for now

**Comment by shashwatak** [comment]
sorry, that was really dumb =(

**Comment by ianrust** [comment]
woooooops

**Pull request merged**
